---
title: "walkability tool"
author: "Benjamin Labohm"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, message=FALSE, warning=FALSE}

# Directories
projectDir <- "D:/seafiles_new/Mycloud/AgeingWell_data/"
dataDir <- paste0(projectDir, "data/")
output_folder <- paste0(dataDir, "/output_neighborhood_data/")
libDir <- paste0(projectDir, "lib/")
#update.packages(libDir)

# load functions
source(paste0(getwd(), "/walkability_tool_funs.R"))

# (Install and) load required packages in / from lib directory
req_pkg = c("sfnetworks", "lwgeom", "terra", "sf", 
            "tidygraph", "tidyr", "dplyr")
safe_load(package_list = req_pkg, library_dir = libDir)


```

## Get paths to input files

```{r get paths}
# Add identifier string to all final output that will serve as input for model
# -> list data to input into model from output folder
# -> separate to raster and vector data
# -> use listed data as parameters that will be calculated all in the same way
#input_files <- list.files(dataDir, pattern = "^_", full.names = TRUE)
raster_input <- list.files(paste0(dataDir, "/raster_input"), #pattern = "^_", 
                           full.names = TRUE)
vector_input <- list.files(paste0(dataDir, "/vector_input"),# pattern = "^_", 
                           full.names = TRUE)
```




## Snap to network

```{r create neighborhood data set, message=FALSE, warning=FALSE}

# Idea:
# Start with max(d) (+security buffer?):
#   Create the clean sfnetwork
#   Add raster data / LS to edge data (use the function you already created)
#   Save network + edge data / buildings / pois
# Do shortest path workflow from building_entries to POIs / park entries (merge destination datasets and give park entry etc. a Dimension attribute)
#
# Extract Distance + raster variables per Dimension category

# Create output directory if it doesnt exist
clean_dir_create(output_folder)

# Open the File containing LOR
lor_sf <- read_sf(vector_input[grepl("lor", vector_input)])

# Create vector of walking distances to iterate through
distances <- seq(from = 100, 
                 to = 1000,
                 b = 100)

# Buffer distance for data input
max_d <- max(distances) + 100

# Iterate through individual LORs
# j <- 1
for(j in 1:nrow(lor_sf)) {

  # First step: gather all data located in target LOR from data sources
  # in a single data frame
  # Open buildings in target LOR
  buildings <- vect_input_wkt(vector_input[grepl("build", vector_input)],
                              st_as_text(lor_sf$geom[j,]))
########################################################################
  # buffer LOR by distance (d) and load POIS / network in buffered area
  lor_buff <- st_as_text(st_buffer(lor_sf$geom[j,], max_d))
  
  # Open POIs in target LOR
  osm_pois <- vect_input_wkt(vector_input[grepl("poi", vector_input)],
                             lor_buff)
  # Open network in target LOR
  osm_network <- vect_input_wkt(vector_input[grepl("network", vector_input)],
                                lor_buff)

  # join raster data to network
  raster_names <- c(gsub(".*/|\\.tif", "", raster_input), "geom")
  raster_data <- 
    rast_input(raster_input,
               osm_network) %>%
    st_drop_geometry() %>% 
    select(matches("Class_Name")) %>% 
    setNames(raster_names)

  # load local significance data
  local_significance <-
    vect_input_wkt(vector_input[grepl("local", vector_input)],
                   lor_buff) %>%
    st_buffer(1)

  # convert osm network into sf network object
  osm_sf_network <- osm_network %>%
    bind_cols(raster_data) %>%
    st_join(local_significance) %>%
    make_sf_network()

  # Find building and POI entry points and blend them into network
  # Nearest point of building polygon on network
  nearest_id <- st_nearest_feature(buildings, osm_network)
  np_build_network <-
    st_nearest_points(buildings,
                      osm_network$geom[nearest_id],
                      pairwise = TRUE) %>%
    st_cast("POINT") %>%
    st_as_sf() %>%
    rename(geom = x) %>%
    slice(seq(2, nrow(.), 2)) %>%
    bind_cols(st_drop_geometry(buildings))

  # building entries
  # building_entries <- np_build_network %>%
  #   blender(osm_sf_network, .) %>%
  #   activate("nodes") %>%
  #   st_as_sf() %>%
  #   filter(!is.na(address))

  # POI entries
  poi_entries <- osm_pois %>%
    blender(osm_sf_network, .) %>%
    activate("nodes") %>%
    st_as_sf() %>%
    filter(!is.na(Dimension))

  # Create edge info df with length, ls, greenness
  edge_info_df <- osm_sf_network %>%
    activate("edges") %>%
    st_as_sf()

  # Second step: Routing between buildings and POIs and calculation of indices
  # create OD cost matrix between buildings and POIs for nearest network distance
  net_cost <- st_network_cost(osm_sf_network, np_build_network, poi_entries)

  # d <- 100
  for (d in distances) {
    print(d)

    # Names and IDs of POIs that are in distance of respective buildings
    in_dist <- apply(net_cost, 1,
                     function(x) poi_entries$Dimension[which(x <= d)])
    in_dist_id <- apply(net_cost, 1, function(x) which(x <= d))

    # Routing between buildings and POIs
    n <- 1
    edge_paths <- data.frame()
    while (length(edge_paths) == 0) {
      try({
        edge_paths <-
          st_network_paths(x = osm_sf_network, 
                           from = np_build_network[n,],
                           to = poi_entries$geom[in_dist_id[[n]]]) %>%
          pull(edge_paths)
        }) 
      if(length(edge_paths) == 0) n <- n + 1
      }

    # Extract data along ways from building entry to POIs and store in temporary
    # data frame
    tmp_out <- 
      tibble(Dimension = in_dist[[n]], edge_paths) %>%
      mutate(net_dist = sapply(edge_paths,
                               function(x) sum(edge_info_df$weight[x],
                                               na.rm = TRUE)),
             local_significance = sapply(edge_paths,
                                         function(x) sum(edge_info_df$ls[x],
                                                         na.rm = TRUE)),
             greenness = sapply(edge_paths,
                                function(x) sum(edge_info_df$greenness[x],
                                                na.rm = TRUE))) %>%
      group_by(Dimension) %>%
      summarise(avg_net_dist = mean(net_dist, na.rm = TRUE),
                min_net_dist = min(net_dist, na.rm = TRUE),
                quantity = n(),
                avg_greenness = mean(greenness, na.rm = TRUE),
                avg_local_significance = mean(local_significance, na.rm = TRUE),
                max_local_significance = max(local_significance, na.rm = TRUE)) %>%
      mutate(address = np_build_network$address[n])

    for(i in (n+1):nrow(np_build_network)){
      edge_paths <- np_build_network[i,] %>%
        st_network_paths(x = osm_sf_network, from = .,
                         to = poi_entries$geom[in_dist_id[[i]]]) %>%
        pull(edge_paths)
      if (length(edge_paths) == 0) next
      tmp_out <- tibble(Dimension = in_dist[[i]], edge_paths) %>%
        mutate(net_dist = sapply(edge_paths,
                                 function(x) sum(edge_info_df$weight[x],
                                                 na.rm = TRUE)),
               local_significance = sapply(edge_paths,
                                           function(x) sum(edge_info_df$ls[x],
                                                           na.rm = TRUE)),
               greenness = sapply(edge_paths,
                                  function(x) sum(edge_info_df$greenness[x],
                                                  na.rm = TRUE))) %>%
        group_by(Dimension) %>%
        summarise(avg_net_dist = mean(net_dist, na.rm = TRUE),
                  min_net_dist = min(net_dist, na.rm = TRUE),
                  quantity = n(),
                  avg_greenness = mean(greenness, na.rm = TRUE),
                  avg_local_significance = mean(local_significance, na.rm = TRUE),
                  max_local_significance = max(local_significance, na.rm = TRUE)) %>%
        mutate(address = np_build_network$address[i]) %>%
        bind_rows(tmp_out, .)
    }

    tmp_out %>% 
      distinct() %>% 
      tidyr::pivot_wider(id_cols = address,
                        names_from = Dimension,
                        values_from = -c(Dimension, address)) %>%
      right_join(buildings) %>%
      write_sf(paste0(output_folder,
                      "/neighborhood_data_",
                      lor_sf$PLR_NAME[j],
                      "_", d, "m",
                      ".gpkg"),
               append = FALSE)
  }
}

```

```{r}
distances <- c(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000
               )

nh_data_files <- list.files(output_folder, full.names = TRUE)

#d <- 100
for (d in distances) {
  filtered_files <- nh_data_files[grepl(paste0("[^a]_" ,d , "m"),
                                        nh_data_files)]
  output_file_name <- paste0(output_folder,
                             "neighborhood_data_", d, "m.gpkg")
  if (file.exists(output_file_name)) unlink(output_file_name, force = TRUE)
  nh_data_tmp  <- read_sf(filtered_files[1])
  for (nh_file in filtered_files[2:length(filtered_files)]) {
    nh_data_tmp <-
      read_sf(nh_file) %>% 
      bind_rows(nh_data_tmp, .)
  }
  write_sf(nh_data_tmp, output_file_name, append = FALSE)
}

nh_data_files_dist <- list.files(output_folder, full.names = TRUE, pattern = "a_\\d*m")
output_file_name <- paste0(output_folder, "neighborhood_data_complete.gpkg")
if (file.exists(output_file_name)) unlink(output_file_name, force = TRUE)

nh_data_complete_tmp  <- read_sf(nh_data_files_dist[1]) %>% 
  mutate(network_distance = gsub(".*data_|.gpkg", "", nh_data_files_dist[1]))
for (nh_file in nh_data_files_dist[2:length(nh_data_files_dist)]) {
  nh_data_complete_tmp <-
    read_sf(nh_file) %>% 
    mutate(network_distance = gsub(".*data_|.gpkg", "", nh_file)) %>% 
    bind_rows(nh_data_complete_tmp, .)
}
write_sf(nh_data_complete_tmp, output_file_name, append = FALSE)
nh_data_complete_tmp %>% 
  st_drop_geometry() %>% 
  write.csv(gsub(".gpkg", ".csv", output_file_name))
```


```{r}
#clean output
nh_data_complete <- read_sf(output_file_name) %>% 
  mutate(address = trimws(address)) %>% 
  group_by(address, network_distance) %>% 
  summarise(across(everything(), .fns = \(x) first(x)))

nh_data_wide <- nh_data_complete %>%  
  pivot_wider(id_cols = c(address, geom), 
              names_from = network_distance,
              values_from = -c(address, network_distance, geom)
    )

nh_data_complete %>% 
  st_drop_geometry() %>% 
  write.csv(gsub(".gpkg", "_long_v2-2.csv", output_file_name))
nh_data_complete %>% 
  write_sf(gsub(".gpkg", "_long_v2-2.gpkg", output_file_name))

nh_data_wide %>% 
  st_drop_geometry() %>% 
  write.csv(gsub(".gpkg", "_wide_v2-2.csv", output_file_name))
nh_data_wide %>% 
  write_sf(gsub(".gpkg", "_wide_v2-2.gpkg", output_file_name))

```