---
title: "1-tcd_pre-processing_tiling"
author: "Benjamin Labohm"
date: "`r Sys.Date()`"
output: html_document
---

# Pre-processing
## Cut the large TCD data sets into 100x100km tiles to prepare the data for later parallel processing

```{r setup, eval=FALSE}
# Load packages
library(dplyr)
library(terra)
library(sf)
# Use github directory as working directory
working_directory <- "D:/github/forest_dynamics/"
data_directory <- paste0(working_directory, "data/")
source(paste0(working_directory,
              "processing/2_tcd_processing_Step_1_and_2_general_funs.R"))
# TCD raw directories (download data from: https://land.copernicus.eu/en/products/high-resolution-layer-tree-cover-density:
tcd12_directory <- "~/TCD_2012_020m_eu_03035_d03_full.tif"
tcd18_directory <- "~/DATA/TCD_2018_010m_eu_03035_V2_0.tif"

```


```{r reference grid, eval=FALSE}

# Using the INSPIRE reference grid
ref_tif <- paste0(data_directory, "inspire_grid.tif")
ref_rst <- rast(ref_tif)
ref_rst[ref_rst < 1] <- NA

# Template sf object for intersecting data
tmp_sf <- terra::as.polygons(ref_rst, dissolve = TRUE) %>% 
  st_as_sf()

```


```{r no data grid, eval=FALSE}

# create a grid covering Europe land masses
no_data_grid <- ref_rst %>%   
  st_make_grid(., cellsize = 1e5) %>%
  st_as_sf() %>% 
  sf::st_filter(tmp_sf, .pred = st_intersects)

```


```{r raster input, eval=FALSE}

# Input TCD data
tcd12_raw <- rast(tcd12_directory)
tcd18_raw <- rast(tcd18_directory)

```


```{r tiling, eval=FALSE}

# Splitting large raster into smaller pieces
# per tile: read data from large raster and write to file
# (make large raster serializeable)
for (i in 1:nrow(nd_grid)) {
  message(i, " of ", nrow(nd_grid))
  # Data input and processing
  tile <- vect(nd_grid$x[i])
  tcd12_tile <- crop(tcd12, tile)  
  tcd18_tile <- crop(tcd18, tile) 
  # Data output
  out_dir_12 <- paste0(data_dir, "tcd_2012_raw_100km/")
  raster_out(tcd12_tile, out_dir_12, "tcd_2012_", i)
  out_dir_18 <- paste0(data_dir, "tcd_2018_raw_100km/")
  raster_out(tcd18_tile, out_dir_18, "tcd_2018_", i)
}

```


```{r no data mask, eval=FALSE}

# Create the no-data raster for later masking
tcd12_list <- list.files(paste0(data_dir, "tcd_2012_raw_100km/"), 
                         full.names = TRUE, pattern = ".tif$")
tcd18_list <- list.files(paste0(data_dir, "tcd_2018_raw_100km/"), 
                         full.names = TRUE, pattern = ".tif$")
data_df <- tibble(n = 1:length(tcd12_list), 
                 tcd12 = tcd12_list,
                 tcd18 = tcd18_list) 
data_list <- data_df %>% 
   split(., .$n)

# Aggregating raster
no_data_tiling <- function(data_vector){
  
  # Input
  data_dir <- "Z:/ch/data/"  
  i <- strsplit(data_vector$tcd12, "2012_")[[1]] %>% 
    last() %>% 
    sub("\\.tif","",.)
  
  tcd12 <- rast(data_vector$tcd12) * 1
  tcd18 <- aggregate(rast(data_vector$tcd18), fact = 2, fun = max)
  
  # Processing
  tcd12[tcd12 < 101] <- 0 
  tcd12[tcd12 > 100] <- 1 
  tcd18[tcd18 < 101] <- 0 
  tcd18[tcd18 > 100] <- 1 
  nd <- tcd12 + tcd18
  nd[nd >= 1] <- 1
  nd <- aggregate(nd, fact = 50, fun = max)
  
  # Output
  out_dir <- paste0(data_dir, "no_data_tiles_1km/")
  raster_out(raster = nd, directory = out_dir,
             string = "no_data_1km_", i = i, dtype = "LOG1S")
  # Clean up ram
  clean_up(environment())
  
}

# Parallel execution
par_exec(data_list, no_data_tiling)

```