
---
title: "osm_download_and_check"
author: "Benjamin Labohm"
date: "`r Sys.Date()`"
output: html_document
---

## Packages
Loading required packages

```{r dirs and packages, echo=FALSE}
# Directories
projectDir <- "D:/seafiles_new/Mycloud/AgeingWell/"
dataDir <- paste0(projectDir, "data/")
libDir <- paste0(projectDir, "lib/")

# Package loading
req_pkg = c("dplyr", "tibble", "tidyr", "sf", "osmdata", "readxl", "httr2", "lubridate")
req_pkg_install <- setdiff(req_pkg, rownames(installed.packages(lib = libDir)))
lapply(req_pkg_install, install.packages, character.only = TRUE, lib = libDir)
lapply(req_pkg, require, character.only = TRUE, lib = libDir)

# load functions
getwd() %>%
    paste0("/osm_download_funs.R") %>%
    source()

```

## Data
Load input data
- target LOR
- target OSM keys

```{r data input}
# load LOR polygons
lor_path <- paste0(dataDir, "lor_target_plr.gpkg")
lor_polygons <- read_sf(lor_path)
plot(lor_polygons$geom)  

# target OSM keys
target_key_path <- paste0(dataDir, "osm_poi_classification.csv")
target_keys <- read.csv2(target_key_path) %>% 
  pull(key) %>% 
  unique()
target_values <- read.csv2(target_key_path) %>% 
  pull(value) %>% 
  unique()

target_keys
#paste(c(target_values), sep = "|")

```

## Download OSM
Download OSM data in target LOR
- by LOR
- by key
- save raw data as osm_raw.gpkg

```{r download OSM}
# by LOR
# i <- 1
# key <- target_keys[2]

# Path for saving raw OSM data
d <- 1e3
osm_raw_dir <- paste0(dataDir, "osm_poi_raw/")
clean_dir_create(osm_raw_dir)

for (i in 1:nrow(lor_polygons)) {

  target_lor <- lor_polygons[i,]

  for (key in target_keys) {
    
    osm_raw_path <- paste0(osm_raw_dir, target_lor$PLR_NAME, ".gpkg")

    osm_data_tmp <- OSM_downloader(loc = target_lor, key = key, d = d)
    osm_data_tmp$osm_points %>% 
      select(matches(paste0("^", key, "$"))) %>% 
      na.omit() %>%
      rename(value = 1) %>% 
      mutate("key" = key) %>% 
      write_sf(osm_raw_path, append = TRUE)
    
  }
}

```

## Filter OSM
- filter for values
- save filtered data as osm_clean.gpkg

```{r inspect OSM}
# list files in osm raw directory
# osm_raw_paths <- list.files(osm_raw_dir, full.names = TRUE)
# osm_clean_dir <- paste0(dataDir, "osm_poi_spat_filter/")
# if (!dir.exists(osm_clean_dir)) dir.create(osm_clean_dir)
# 
# # filter files spatially and by values
# # lor_name <- lor_polygons$BZR_NAME[1]
# # Distance parameter
# d <- 1000
# for (lor_name in lor_polygons$PLR_NAME) {
#   
#   lor_polygon <- filter(lor_polygons, PLR_NAME == lor_name) %>% 
#     st_buffer(d)
#   grep(lor_name, osm_raw_paths, value = TRUE) %>%
#     read_sf() %>% 
#     st_transform(st_crs(lor_polygon)) %>% 
#     st_filter(lor_polygon) %>% 
#     #filter(value %in% target_values) %>% 
#     write_sf(paste0(osm_clean_dir, lor_name, ".gpkg"), overwrite = TRUE)
#     
# }

```

## Test
Inspect OSM data for completeness 
- how many 'highways' have smoothness / surface params?
- [https://dashboard.ohsome.org]

```{r inspect OSM}
# load csv file with osm keys
key_base_df <- read.csv2(target_key_path)

# retrieve all OSM keys in study area
osm_raw_paths <- list.files(osm_raw_dir, full.names = TRUE) 
osm_key_df <- osm_raw_paths[1] %>% 
  read_sf() %>% 
  st_drop_geometry() #%>% 
  #distinct()
for (osm_sf_path in osm_raw_paths[2:length(osm_raw_paths)]) {
  
  osm_key_df <- osm_sf_path %>% 
    read_sf() %>% 
    st_drop_geometry() %>% 
    #distinct() %>% 
    bind_rows(osm_key_df)
  
}

osm_key_df <- osm_key_df %>% 
  group_by(value, key) %>% 
  summarise(n_value = n())

# bind full OSM key df to key csv file
osm_key_df_full <- osm_key_df %>%
  #distinct() %>% 
  full_join(key_base_df) %>% 
  mutate(group = if_else(is.na(group), "other", group),
         group = if_else(grepl("supermark", group), "sustenance", group)) %>% 
  filter(!grepl("\\*|^no$|^yes$", value))

osm_key_df_full %>% 
  arrange(group) %>% 
  write.csv(paste0(dataDir, "osm_class_df.csv"), 
          row.names = FALSE)

osm_key_df_full %>% 
  filter(!is.na(n_value),
         n_value >= 3) %>% 
  arrange(group, value) %>% 
  write.csv(paste0(dataDir, "osm_poi_classification_table.csv"),
            row.names = FALSE)

# load OSM files and join with osm key df full
osm_key_sf <- osm_raw_paths[1] %>% 
  read_sf()
for (osm_sf_path in osm_raw_paths[2:length(osm_raw_paths)]) {
  
  osm_key_sf <- osm_sf_path %>% 
    read_sf() %>% 
    bind_rows(osm_key_sf)
  
}

# classify OSM data into groups with osm key df
osm_key_sf %>% 
  left_join(key_base_df) %>% 
  select(-c(n_value)) %>% 
  write_sf(paste0(dataDir, "osm_class_group.gpkg"), overwrite = TRUE)
```


```{r join OSM with dimension}
dim_class_table <- 
  read_excel(paste0(dataDir, "osm_poi_classification.xlsx")) %>% 
  select(value, Dimension)
  
osm_poi_sf <- read_sf(paste0(dataDir, "osm_class_group.gpkg"))

osm_poi_dim <- dplyr::left_join(osm_poi_sf, dim_class_table) %>% 
  mutate(Dimension = gsub("/", "_", Dimension),
         Dimension = gsub("social", "Social", Dimension),
         Dimension = gsub("physical", "Physical", Dimension)) %>%  
  filter(!is.na(Dimension)) %>% 
  st_transform(25833)

write_sf(osm_poi_dim, paste0(dataDir, "_osm_poi_dim.gpkg"))

```